In [3]:
#! wget -P ../data/raw https://aqua.kingcounty.gov/extranet/assessor/Real%20Property%20Sales.zip
#! unzip ../data/raw/Real\ Property\ Sales.zip
#! wget -P ../data/raw https://aqua.kingcounty.gov/extranet/assessor/Residential%20Building.zip
#! unzip ../data/raw/Residential\ Building.zip
#! wget -P ../data/raw https://aqua.kingcounty.gov/extranet/assessor/Parcel.zip
#! unzip ../data/raw/Parcel.zip
#! wget -P ../data/raw https://aqua.kingcounty.gov/extranet/assessor/Lookup.zip
#! unzip ../data/raw/Lookup.zip

--2020-06-14 16:22:23--  https://aqua.kingcounty.gov/extranet/assessor/Real%20Property%20Sales.zip
Resolving aqua.kingcounty.gov (aqua.kingcounty.gov)... 146.129.240.28
Connecting to aqua.kingcounty.gov (aqua.kingcounty.gov)|146.129.240.28|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 128312536 (122M) [application/x-zip-compressed]
Saving to: ‘../data/raw/Real Property Sales.zip’

Real Property Sales 100%[===================>] 122.37M  5.26MB/s    in 23s

2020-06-14 16:22:46 (5.34 MB/s) - ‘../data/raw/Real Property Sales.zip’ saved [128312536/128312536]

Archive:  ../data/raw/Real Property Sales.zip
  inflating: EXTR_RPSale.csv
--2020-06-14 16:22:49--  https://aqua.kingcounty.gov/extranet/assessor/Residential%20Building.zip
Resolving aqua.kingcounty.gov (aqua.kingcounty.gov)... 146.129.240.28
Connecting to aqua.kingcounty.gov (aqua.kingcounty.gov)|146.129.240.28|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24615574 (23M) [application/x-zip-compressed]
Saving to: ‘../data/raw/Residential Building.zip’

Residential Buildin 100%[===================>]  23.47M  5.67MB/s    in 4.3s

2020-06-14 16:22:53 (5.46 MB/s) - ‘../data/raw/Residential Building.zip’ saved [24615574/24615574]

Archive:  ../data/raw/Residential Building.zip
  inflating: EXTR_ResBldg.csv
--2020-06-14 16:22:55--  https://aqua.kingcounty.gov/extranet/assessor/Parcel.zip
Resolving aqua.kingcounty.gov (aqua.kingcounty.gov)... 146.129.240.28
Connecting to aqua.kingcounty.gov (aqua.kingcounty.gov)|146.129.240.28|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 30467367 (29M) [application/x-zip-compressed]
Saving to: ‘../data/raw/Parcel.zip’

Parcel.zip          100%[===================>]  29.06M  5.59MB/s    in 5.3s

2020-06-14 16:23:00 (5.46 MB/s) - ‘../data/raw/Parcel.zip’ saved [30467367/30467367]

Archive:  ../data/raw/Parcel.zip
  inflating: EXTR_Parcel.csv
--2020-06-14 16:23:01--  https://aqua.kingcounty.gov/extranet/assessor/Lookup.zip
Resolving aqua.kingcounty.gov (aqua.kingcounty.gov)... 146.129.240.28
Connecting to aqua.kingcounty.gov (aqua.kingcounty.gov)|146.129.240.28|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16114 (16K) [application/x-zip-compressed]
Saving to: ‘../data/raw/Lookup.zip.1’

Lookup.zip.1        100%[===================>]  15.74K  --.-KB/s    in 0s

2020-06-14 16:23:01 (53.7 MB/s) - ‘../data/raw/Lookup.zip.1’ saved [16114/16114]

Archive:  ../data/raw/Lookup.zip
replace EXTR_LookUp.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: ^C

In [4]:
import pandas as pd
import datetime as dt
Real_Prop = pd.read_csv("EXTR_RPSale.csv")
Res_Bldg = pd.read_csv("EXTR_ResBldg.csv")
Parcel = pd.read_csv("EXTR_Parcel.csv", encoding='latin-1')
codes = pd.read_csv('EXTR_LookUp.csv')

/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (1,2) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
Real_Prop['DocumentDate'] = pd.to_datetime(Real_Prop['DocumentDate'])
Real_Prop19 = Real_Prop[Real_Prop['DocumentDate'].dt.year == 2019]
Real_Prop19

,ExciseTaxNbr,Major,Minor,DocumentDate,SalePrice,RecordingNbr,Volume,Page,PlatNbr,PlatType,...,PropertyType,PrincipalUse,SaleInstrument,AFForestLand,AFCurrentUseLand,AFNonProfitUse,AFHistoricProperty,SaleReason,PropertyClass,SaleWarning
4,3027422,213043,120,2019-12-20,560000,20191226000848,,,,,...,11,6,3,N,N,N,N,1,8,
118,2999169,919715,200,2019-07-08,192000,20190712001080,,,,,...,3,2,3,N,N,N,N,1,3,
144,3000673,894444,200,2019-06-26,185000,20190722001395,,,,,...,3,2,3,N,N,N,N,1,3,
164,3002257,940652,630,2019-07-22,435000,20190730001339,,,,,...,11,6,3,N,N,N,N,1,8,
445,2980836,937630,695,2019-03-28,550000,20190404001008,,,,,...,3,6,3,N,N,N,N,1,8,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2089056,3004408,66000,2210,2019-08-07,41040000,20190812000849,,,,,...,3,7,22,N,N,N,N,18,2,45
2089057,3004408,66000,2225,2019-08-07,41040000,20190812000849,,,,,...,3,7,22,N,N,N,N,18,2,45
2089058,3004408,66000,2195,2019-08-07,41040000,20190812000849,,,,,...,3,7,22,N,N,N,N,18,2,45
2089059,3004408,66000,2220,2019-08-07,41040000,20190812000849,,,,,...,3,7,22,N,N,N,N,18,2,45
2089082,3009227,192300,170,2019-09-03,1550000,20190909000838,,,,,...,11,6,3,N,N,N,N,1,8,

In [6]:
colnames = Real_Prop19.columns
colnames = [x.lower() for x in colnames]
Real_Prop19.columns = colnames

In [7]:
Real_Prop19.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 61363 entries, 4 to 2089082
Data columns (total 24 columns):
excisetaxnbr          61363 non-null int64
major                 61363 non-null object
minor                 61363 non-null object
documentdate          61363 non-null datetime64[ns]
saleprice             61363 non-null int64
recordingnbr          61363 non-null object
volume                61363 non-null object
page                  61363 non-null object
platnbr               61363 non-null object
plattype              61363 non-null object
platlot               61363 non-null object
platblock             61363 non-null object
sellername            61363 non-null object
buyername             61363 non-null object
propertytype          61363 non-null int64
principaluse          61363 non-null int64
saleinstrument        61363 non-null int64
afforestland          61363 non-null object
afcurrentuseland      61363 non-null object
afnonprofituse        61363 non-null object
afhistoricproperty    61363 non-null object
salereason            61363 non-null int64
propertyclass         61363 non-null int64
salewarning           61363 non-null object
dtypes: datetime64[ns](1), int64(7), object(16)
memory usage: 11.7+ MB

In [8]:
Real_Prop19['major'] = Real_Prop19['major'].astype(str)

/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [9]:
def major_padded(row):
    if len(row) == 6:
        return row
    elif len(row) == 5:
        return '0'+row
    elif len(row) == 4:
        return '00'+row
    elif len(row) == 3:
        return '000'+row
    elif len(row) == 2:
        return '0000'+row
    elif len(row) == 1:
        return '00000'+row
    else:
        return '000000'
Real_Prop19['major'] = Real_Prop19.major.apply(major_padded)
Real_Prop19

/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()

,excisetaxnbr,major,minor,documentdate,saleprice,recordingnbr,volume,page,platnbr,plattype,...,propertytype,principaluse,saleinstrument,afforestland,afcurrentuseland,afnonprofituse,afhistoricproperty,salereason,propertyclass,salewarning
4,3027422,213043,120,2019-12-20,560000,20191226000848,,,,,...,11,6,3,N,N,N,N,1,8,
118,2999169,919715,200,2019-07-08,192000,20190712001080,,,,,...,3,2,3,N,N,N,N,1,3,
144,3000673,894444,200,2019-06-26,185000,20190722001395,,,,,...,3,2,3,N,N,N,N,1,3,
164,3002257,940652,630,2019-07-22,435000,20190730001339,,,,,...,11,6,3,N,N,N,N,1,8,
445,2980836,937630,695,2019-03-28,550000,20190404001008,,,,,...,3,6,3,N,N,N,N,1,8,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2089056,3004408,066000,2210,2019-08-07,41040000,20190812000849,,,,,...,3,7,22,N,N,N,N,18,2,45
2089057,3004408,066000,2225,2019-08-07,41040000,20190812000849,,,,,...,3,7,22,N,N,N,N,18,2,45
2089058,3004408,066000,2195,2019-08-07,41040000,20190812000849,,,,,...,3,7,22,N,N,N,N,18,2,45
2089059,3004408,066000,2220,2019-08-07,41040000,20190812000849,,,,,...,3,7,22,N,N,N,N,18,2,45
2089082,3009227,192300,170,2019-09-03,1550000,20190909000838,,,,,...,11,6,3,N,N,N,N,1,8,

In [10]:
Real_Prop19['minor'] = Real_Prop19['minor'].astype(str)

/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [11]:
def minor_padded(row):
    if len(row) == 4:
        return row
    elif len(row) == 3: 
        return '0'+row
    elif len(row) == 2:
        return '00'+row
    elif len(row) == 1:
        return '000'+row
    else:
        return '0000'
Real_Prop19['minor'] = Real_Prop19.minor.apply(minor_padded)

/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

In [12]:
Real_Prop19

,excisetaxnbr,major,minor,documentdate,saleprice,recordingnbr,volume,page,platnbr,plattype,...,propertytype,principaluse,saleinstrument,afforestland,afcurrentuseland,afnonprofituse,afhistoricproperty,salereason,propertyclass,salewarning
4,3027422,213043,0120,2019-12-20,560000,20191226000848,,,,,...,11,6,3,N,N,N,N,1,8,
118,2999169,919715,0200,2019-07-08,192000,20190712001080,,,,,...,3,2,3,N,N,N,N,1,3,
144,3000673,894444,0200,2019-06-26,185000,20190722001395,,,,,...,3,2,3,N,N,N,N,1,3,
164,3002257,940652,0630,2019-07-22,435000,20190730001339,,,,,...,11,6,3,N,N,N,N,1,8,
445,2980836,937630,0695,2019-03-28,550000,20190404001008,,,,,...,3,6,3,N,N,N,N,1,8,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2089056,3004408,066000,2210,2019-08-07,41040000,20190812000849,,,,,...,3,7,22,N,N,N,N,18,2,45
2089057,3004408,066000,2225,2019-08-07,41040000,20190812000849,,,,,...,3,7,22,N,N,N,N,18,2,45
2089058,3004408,066000,2195,2019-08-07,41040000,20190812000849,,,,,...,3,7,22,N,N,N,N,18,2,45
2089059,3004408,066000,2220,2019-08-07,41040000,20190812000849,,,,,...,3,7,22,N,N,N,N,18,2,45
2089082,3009227,192300,0170,2019-09-03,1550000,20190909000838,,,,,...,11,6,3,N,N,N,N,1,8,

In [13]:
Real_Prop19['major_minor'] = Real_Prop19['major']+Real_Prop19['minor']

/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [14]:
Real_Prop19

,excisetaxnbr,major,minor,documentdate,saleprice,recordingnbr,volume,page,platnbr,plattype,...,principaluse,saleinstrument,afforestland,afcurrentuseland,afnonprofituse,afhistoricproperty,salereason,propertyclass,salewarning,major_minor
4,3027422,213043,0120,2019-12-20,560000,20191226000848,,,,,...,6,3,N,N,N,N,1,8,,2130430120
118,2999169,919715,0200,2019-07-08,192000,20190712001080,,,,,...,2,3,N,N,N,N,1,3,,9197150200
144,3000673,894444,0200,2019-06-26,185000,20190722001395,,,,,...,2,3,N,N,N,N,1,3,,8944440200
164,3002257,940652,0630,2019-07-22,435000,20190730001339,,,,,...,6,3,N,N,N,N,1,8,,9406520630
445,2980836,937630,0695,2019-03-28,550000,20190404001008,,,,,...,6,3,N,N,N,N,1,8,,9376300695
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2089056,3004408,066000,2210,2019-08-07,41040000,20190812000849,,,,,...,7,22,N,N,N,N,18,2,45,0660002210
2089057,3004408,066000,2225,2019-08-07,41040000,20190812000849,,,,,...,7,22,N,N,N,N,18,2,45,0660002225
2089058,3004408,066000,2195,2019-08-07,41040000,20190812000849,,,,,...,7,22,N,N,N,N,18,2,45,0660002195
2089059,3004408,066000,2220,2019-08-07,41040000,20190812000849,,,,,...,7,22,N,N,N,N,18,2,45,0660002220
2089082,3009227,192300,0170,2019-09-03,1550000,20190909000838,,,,,...,6,3,N,N,N,N,1,8,,1923000170

In [15]:
col_name = 'major_minor'
last_col = Real_Prop19.pop(col_name)
Real_Prop19.insert(1, col_name, last_col)

In [16]:
Real_Prop19.minor.unique()

array(['0120', '0200', '0630', ..., '2561', '9437', '4239'], dtype=object)

In [17]:
Res_Bldg.rename(columns=str.lower, inplace=True)

In [18]:
Res_Bldg['major'] = Res_Bldg['major'].astype(str)
Res_Bldg['minor'] = Res_Bldg['minor'].astype(str)

In [19]:
Res_Bldg['major'] = Res_Bldg['major'].apply(major_padded)
Res_Bldg['minor'] = Res_Bldg['minor'].apply(minor_padded)

In [20]:
Res_Bldg['major_minor'] = Res_Bldg['major']+Res_Bldg['minor']

In [21]:
col_name = 'major_minor'
last_col = Res_Bldg.pop(col_name)
Res_Bldg.insert(0, col_name, last_col)

In [22]:
Res_Bldg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 515263 entries, 0 to 515262
Data columns (total 51 columns):
major_minor           515263 non-null object
major                 515263 non-null object
minor                 515263 non-null object
bldgnbr               515263 non-null int64
nbrlivingunits        515263 non-null int64
address               515263 non-null object
buildingnumber        515263 non-null object
fraction              515263 non-null object
directionprefix       514721 non-null object
streetname            515263 non-null object
streettype            515263 non-null object
directionsuffix       514721 non-null object
zipcode               469778 non-null object
stories               515263 non-null float64
bldggrade             515263 non-null int64
bldggradevar          515263 non-null int64
sqft1stfloor          515263 non-null int64
sqfthalffloor         515263 non-null int64
sqft2ndfloor          515263 non-null int64
sqftupperfloor        515263 non-null int64
sqftunfinfull         515263 non-null int64
sqftunfinhalf         515263 non-null int64
sqfttotliving         515263 non-null int64
sqfttotbasement       515263 non-null int64
sqftfinbasement       515263 non-null int64
finbasementgrade      515263 non-null int64
sqftgaragebasement    515263 non-null int64
sqftgarageattached    515263 non-null int64
daylightbasement      515263 non-null object
sqftopenporch         515263 non-null int64
sqftenclosedporch     515263 non-null int64
sqftdeck              515263 non-null int64
heatsystem            515263 non-null int64
heatsource            515263 non-null int64
brickstone            515263 non-null int64
viewutilization       515263 non-null object
bedrooms              515263 non-null int64
bathhalfcount         515263 non-null int64
bath3qtrcount         515263 non-null int64
bathfullcount         515263 non-null int64
fpsinglestory         515263 non-null int64
fpmultistory          515263 non-null int64
fpfreestanding        515263 non-null int64
fpadditional          515263 non-null int64
yrbuilt               515263 non-null int64
yrrenovated           515263 non-null int64
pcntcomplete          515263 non-null int64
obsolescence          515263 non-null int64
pcntnetcondition      515263 non-null int64
condition             515263 non-null int64
addnlcost             515263 non-null int64
dtypes: float64(1), int64(37), object(13)
memory usage: 200.5+ MB

In [23]:
Parcel.rename(columns=str.lower, inplace=True)

In [24]:
Parcel['major'] = Parcel['major'].astype(str)
Parcel['minor'] = Parcel['minor'].astype(str)

In [25]:
Parcel['major'] = Parcel['major'].apply(major_padded)
Parcel['minor'] = Parcel['minor'].apply(minor_padded)

In [26]:
Parcel['major_minor'] = Parcel['major']+Parcel['minor']

In [27]:
last_col = Parcel.pop(col_name)
Parcel.insert(0, col_name, last_col)

In [28]:
Parcel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614843 entries, 0 to 614842
Data columns (total 82 columns):
major_minor               614843 non-null object
major                     614843 non-null object
minor                     614843 non-null object
propname                  601757 non-null object
platname                  520495 non-null object
platlot                   614843 non-null object
platblock                 614843 non-null object
range                     614843 non-null int64
township                  614843 non-null int64
section                   614843 non-null int64
quartersection            614843 non-null object
proptype                  614843 non-null object
area                      614813 non-null float64
subarea                   614813 non-null float64
specarea                  17332 non-null float64
specsubarea               17332 non-null float64
districtname              614843 non-null object
levycode                  614843 non-null int64
currentzoning             614842 non-null object
hbuasifvacant             614843 non-null int64
hbuasimproved             614843 non-null int64
presentuse                614843 non-null int64
sqftlot                   614843 non-null int64
watersystem               614843 non-null int64
sewersystem               614843 non-null int64
access                    614843 non-null int64
topography                614843 non-null int64
streetsurface             614843 non-null int64
restrictiveszshape        614843 non-null int64
inadequateparking         614843 non-null int64
pcntunusable              614843 non-null int64
unbuildable               614843 non-null bool
mtrainier                 614843 non-null int64
olympics                  614843 non-null int64
cascades                  614843 non-null int64
territorial               614843 non-null int64
seattleskyline            614843 non-null int64
pugetsound                614843 non-null int64
lakewashington            614843 non-null int64
lakesammamish             614843 non-null int64
smalllakerivercreek       614843 non-null int64
otherview                 614843 non-null int64
wfntlocation              614843 non-null int64
wfntfootage               614843 non-null int64
wfntbank                  614843 non-null int64
wfntpoorquality           614843 non-null int64
wfntrestrictedaccess      614843 non-null int64
wfntaccessrights          614843 non-null object
wfntproximityinfluence    614843 non-null object
tidelandshoreland         614843 non-null int64
lotdepthfactor            614843 non-null int64
trafficnoise              614843 non-null int64
airportnoise              614843 non-null int64
powerlines                614843 non-null object
othernuisances            614843 non-null object
nbrbldgsites              614843 non-null int64
contamination             614843 non-null int64
dnrlease                  614843 non-null object
adjacentgolffairway       614843 non-null object
adjacentgreenbelt         614843 non-null object
historicsite              614843 non-null int64
currentusedesignation     614843 non-null int64
nativegrowthprotesmt      614843 non-null object
easements                 614843 non-null object
otherdesignation          614843 non-null object
deedrestrictions          614843 non-null object
developmentrightspurch    614843 non-null object
coalminehazard            614843 non-null object
criticaldrainage          614843 non-null object
erosionhazard             614843 non-null object
landfillbuffer            614843 non-null object
hundredyrfloodplain       614843 non-null object
seismichazard             614843 non-null object
landslidehazard           614843 non-null object
steepslopehazard          614843 non-null object
stream                    614843 non-null object
wetland                   614843 non-null object
speciesofconcern          614843 non-null object
sensitiveareatract        614843 non-null object
waterproblems             614843 non-null object
transpconcurrency         614843 non-null object
otherproblems             614843 non-null object
dtypes: bool(1), float64(4), int64(39), object(38)
memory usage: 380.5+ MB

In [29]:
prop_res = Real_Prop19.merge(Res_Bldg, on='major_minor', how='inner', suffixes=('', '_res' ))

In [30]:
Res_Bldg.merge(Real_Prop19, on='major_minor', suffixes=("", "_rp"))

,major_minor,major,minor,bldgnbr,nbrlivingunits,address,buildingnumber,fraction,directionprefix,streetname,...,propertytype,principaluse,saleinstrument,afforestland,afcurrentuseland,afnonprofituse,afhistoricproperty,salereason,propertyclass,salewarning
0,0461001720,046100,1720,1,1,7330 13TH AVE NW 98117,7330,,,13TH,...,2,6,3,N,N,N,N,1,8,
1,0461004710,046100,4710,1,1,7041 9TH AVE NW,7041,,,9TH,...,11,6,3,N,N,N,N,1,8,
2,0098300030,009830,0030,1,1,1827 298TH CRESENT SE 98024,1827,,,298TH CRESENT,...,11,6,3,N,N,N,N,1,8,
3,0100600800,010060,0800,1,1,33411 28TH PL SW 98023,33411,,,28TH,...,11,6,15,N,N,N,N,1,8,
4,0100600800,010060,0800,1,1,33411 28TH PL SW 98023,33411,,,28TH,...,11,6,3,N,N,N,N,1,8,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43862,3708900034,370890,0034,1,1,3225 W MERCER WAY 98040,3225,,W,MERCER,...,3,6,3,N,N,N,N,1,8,
43863,3723800072,372380,0072,1,1,5419 S LUCILE ST 98118,5419,,S,LUCILE,...,3,6,3,N,N,N,N,1,8,
43864,3728300090,372830,0090,1,1,9033 381ST AVE SE 98065,9033,,,381ST,...,11,6,15,N,N,N,N,1,8,
43865,3750602817,375060,2817,1,1,37419 47TH AVE S 98001,37419,,,47TH,...,11,6,3,N,N,N,N,1,8,
43866,3751602283,375160,2283,1,1,35228 55TH AVE S 98001,35228,,,55TH,...,11,6,3,N,N,N,N,1,8,

In [32]:
#pd.options.display.max_colwidth = 300
#codes[codes['LUType'] == 4]

In [34]:
#Res_Bldg.major_minor

In [35]:
res_rp = Res_Bldg.merge(Real_Prop19, on='major_minor', suffixes=("", "_rp"))

In [36]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline